wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 32
dense_units:
  value: 64
dropout_rate:
  value: 0.8
epochs:
  value: 500
fusion_type:
  value: intermediate
gru_units:
  value: 256
learning_rate:
  value: 0.01
loss:
  value: categorical_crossentropy
modality:
  value: pose
num_gru_layers:
  value: 3
optimizer:
  value: rmsprop
recurrent_regularizer:
  value: l2
sequence_length:
  value: 30
use_bidirectional:
  value: true
use_norm:
  value: false
use_pca:
  value: true
use_stats:
  value: false
