wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 32
dense_units:
  value: 128
dropout_rate:
  value: 0.8
epochs:
  value: 500
fusion_type:
  value: late
learning_rate:
  value: 0.001
loss:
  value: binary_crossentropy
lstm_units:
  value: 64
modality:
  value: audio
num_lstm_layers:
  value: 2
optimizer:
  value: rmsprop
recurrent_regularizer:
  value: l2
sequence_length:
  value: 90
use_bidirectional:
  value: true
use_norm:
  value: false
use_pca:
  value: true
use_stats:
  value: true
