wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 32
dense_units:
  value: 64
dropout_rate:
  value: 0.3
epochs:
  value: 500
fusion_type:
  value: late
learning_rate:
  value: 0.01
loss:
  value: categorical_crossentropy
lstm_units:
  value: 64
modality:
  value: pose
num_lstm_layers:
  value: 1
optimizer:
  value: rmsprop
recurrent_regularizer:
  value: l1_l2
sequence_length:
  value: 30
use_bidirectional:
  value: false
use_norm:
  value: false
use_pca:
  value: false
use_stats:
  value: true
