wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 128
dense_units:
  value: 128
dropout_rate:
  value: 0.8
epochs:
  value: 500
fusion_type:
  value: early
learning_rate:
  value: 0.001
loss:
  value: categorical_crossentropy
lstm_units:
  value: 256
modality:
  value: pose_audio
num_lstm_layers:
  value: 2
optimizer:
  value: adam
recurrent_regularizer:
  value: l1
sequence_length:
  value: 30
use_bidirectional:
  value: true
use_norm:
  value: true
use_pca:
  value: false
use_stats:
  value: true
