wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 32
dense_units:
  value: 128
dropout_rate:
  value: 0
epochs:
  value: 500
fusion_type:
  value: early
gru_units:
  value: 256
learning_rate:
  value: 0.001
loss:
  value: categorical_crossentropy
modality:
  value: audio
num_gru_layers:
  value: 3
optimizer:
  value: adam
recurrent_regularizer:
  value: l2
sequence_length:
  value: 90
use_bidirectional:
  value: true
use_norm:
  value: false
use_pca:
  value: false
use_stats:
  value: true
