wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 128
dense_units:
  value: 64
dropout_rate:
  value: 0.5
epochs:
  value: 500
fusion_type:
  value: late
gru_units:
  value: 128
learning_rate:
  value: 0.001
loss:
  value: categorical_crossentropy
modality:
  value: facial_audio
num_gru_layers:
  value: 1
optimizer:
  value: sgd
recurrent_regularizer:
  value: l1
sequence_length:
  value: 30
use_bidirectional:
  value: false
use_norm:
  value: true
use_pca:
  value: false
use_stats:
  value: true
