wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 64
dense_units:
  value: 128
dropout_rate:
  value: 0
epochs:
  value: 500
fusion_type:
  value: intermediate
gru_units:
  value: 256
learning_rate:
  value: 0.005
loss:
  value: categorical_crossentropy
modality:
  value: pose_facial
num_gru_layers:
  value: 3
optimizer:
  value: adam
recurrent_regularizer:
  value: l2
sequence_length:
  value: 60
use_bidirectional:
  value: false
use_norm:
  value: false
use_pca:
  value: false
use_stats:
  value: true
