wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 128
dense_units:
  value: 128
dropout_rate:
  value: 0.3
epochs:
  value: 500
fusion_type:
  value: intermediate
gru_units:
  value: 64
learning_rate:
  value: 0.001
loss:
  value: categorical_crossentropy
modality:
  value: pose_facial
num_gru_layers:
  value: 3
optimizer:
  value: adam
recurrent_regularizer:
  value: l2
sequence_length:
  value: 30
use_bidirectional:
  value: false
use_norm:
  value: true
use_pca:
  value: false
use_stats:
  value: true
