wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 64
dense_units:
  value: 32
dropout_rate:
  value: 0.8
epochs:
  value: 500
fusion_type:
  value: early
learning_rate:
  value: 0.01
loss:
  value: categorical_crossentropy
lstm_units:
  value: 256
modality:
  value: pose_facial
num_lstm_layers:
  value: 2
optimizer:
  value: adam
recurrent_regularizer:
  value: l1
sequence_length:
  value: 60
use_bidirectional:
  value: false
use_norm:
  value: false
use_pca:
  value: true
use_stats:
  value: false
