wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 128
dense_units:
  value: 32
dropout_rate:
  value: 0.8
epochs:
  value: 500
fusion_type:
  value: late
learning_rate:
  value: 0.01
loss:
  value: categorical_crossentropy
lstm_units:
  value: 64
modality:
  value: pose_audio
num_lstm_layers:
  value: 2
optimizer:
  value: rmsprop
recurrent_regularizer:
  value: l2
sequence_length:
  value: 90
use_bidirectional:
  value: false
use_norm:
  value: true
use_pca:
  value: false
use_stats:
  value: true
