wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 32
dense_units:
  value: 128
dropout_rate:
  value: 0.8
epochs:
  value: 500
fusion_type:
  value: late
gru_units:
  value: 64
learning_rate:
  value: 0.005
loss:
  value: categorical_crossentropy
modality:
  value: combined
num_gru_layers:
  value: 3
optimizer:
  value: rmsprop
recurrent_regularizer:
  value: l1
sequence_length:
  value: 90
use_bidirectional:
  value: false
use_norm:
  value: true
use_pca:
  value: false
use_stats:
  value: false
