wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 128
dense_units:
  value: 64
dropout_rate:
  value: 0.5
epochs:
  value: 500
fusion_type:
  value: late
gru_units:
  value: 256
learning_rate:
  value: 0.005
loss:
  value: categorical_crossentropy
modality:
  value: pose
num_gru_layers:
  value: 1
optimizer:
  value: rmsprop
recurrent_regularizer:
  value: l1
sequence_length:
  value: 60
use_bidirectional:
  value: true
use_norm:
  value: true
use_pca:
  value: false
use_stats:
  value: false
