wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 64
dense_units:
  value: 128
dropout_rate:
  value: 0.5
epochs:
  value: 500
fusion_type:
  value: late
gru_units:
  value: 256
learning_rate:
  value: 0.01
loss:
  value: binary_crossentropy
modality:
  value: audio
num_gru_layers:
  value: 1
optimizer:
  value: sgd
recurrent_regularizer:
  value: l1
sequence_length:
  value: 90
use_bidirectional:
  value: true
use_norm:
  value: true
use_pca:
  value: false
use_stats:
  value: true
