wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 32
dense_units:
  value: 32
dropout_rate:
  value: 0.3
epochs:
  value: 500
fusion_type:
  value: intermediate
gru_units:
  value: 256
learning_rate:
  value: 0.01
loss:
  value: categorical_crossentropy
modality:
  value: facial
num_gru_layers:
  value: 2
optimizer:
  value: sgd
recurrent_regularizer:
  value: l1
sequence_length:
  value: 90
use_bidirectional:
  value: true
use_norm:
  value: false
use_pca:
  value: false
use_stats:
  value: true
