wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 64
dense_units:
  value: 128
dropout_rate:
  value: 0.3
epochs:
  value: 500
fusion_type:
  value: intermediate
learning_rate:
  value: 0.001
loss:
  value: categorical_crossentropy
lstm_units:
  value: 64
modality:
  value: facial_audio
num_lstm_layers:
  value: 1
optimizer:
  value: adadelta
recurrent_regularizer:
  value: l1
sequence_length:
  value: 30
use_bidirectional:
  value: true
use_norm:
  value: true
use_pca:
  value: false
use_stats:
  value: true
