wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 128
dense_units:
  value: 128
dropout_rate:
  value: 0.3
epochs:
  value: 500
fusion_type:
  value: early
learning_rate:
  value: 0.005
loss:
  value: categorical_crossentropy
lstm_units:
  value: 128
modality:
  value: facial_audio
num_lstm_layers:
  value: 1
optimizer:
  value: rmsprop
recurrent_regularizer:
  value: l1
sequence_length:
  value: 90
use_bidirectional:
  value: true
use_norm:
  value: false
use_pca:
  value: false
use_stats:
  value: false
