wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 64
dense_units:
  value: 64
dropout_rate:
  value: 0.8
epochs:
  value: 500
fusion_type:
  value: late
learning_rate:
  value: 0.01
loss:
  value: binary_crossentropy
lstm_units:
  value: 128
modality:
  value: facial
num_lstm_layers:
  value: 3
optimizer:
  value: sgd
recurrent_regularizer:
  value: l1_l2
sequence_length:
  value: 90
use_bidirectional:
  value: true
use_norm:
  value: true
use_pca:
  value: false
use_stats:
  value: true
