wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 64
dense_units:
  value: 64
dropout_rate:
  value: 0
epochs:
  value: 500
fusion_type:
  value: early
learning_rate:
  value: 0.005
loss:
  value: categorical_crossentropy
lstm_units:
  value: 64
modality:
  value: pose
num_lstm_layers:
  value: 1
optimizer:
  value: adam
recurrent_regularizer:
  value: l1_l2
sequence_length:
  value: 30
use_bidirectional:
  value: true
use_norm:
  value: false
use_pca:
  value: false
use_stats:
  value: false
