wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 128
dense_units:
  value: 32
dropout_rate:
  value: 0
epochs:
  value: 500
fusion_type:
  value: early
gru_units:
  value: 64
learning_rate:
  value: 0.01
loss:
  value: categorical_crossentropy
modality:
  value: pose_facial
num_gru_layers:
  value: 3
optimizer:
  value: adam
recurrent_regularizer:
  value: l1
sequence_length:
  value: 30
use_bidirectional:
  value: true
use_norm:
  value: false
use_pca:
  value: true
use_stats:
  value: true
