wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 64
dense_units:
  value: 32
dropout_rate:
  value: 0
epochs:
  value: 500
fusion_type:
  value: early
gru_units:
  value: 256
learning_rate:
  value: 0.001
loss:
  value: categorical_crossentropy
modality:
  value: pose_facial
num_gru_layers:
  value: 1
optimizer:
  value: adam
recurrent_regularizer:
  value: l1_l2
sequence_length:
  value: 60
use_bidirectional:
  value: false
use_norm:
  value: false
use_pca:
  value: false
use_stats:
  value: false
