wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 64
dense_units:
  value: 32
dropout_rate:
  value: 0.3
epochs:
  value: 500
fusion_type:
  value: late
gru_units:
  value: 128
learning_rate:
  value: 0.01
loss:
  value: categorical_crossentropy
modality:
  value: combined
num_gru_layers:
  value: 1
optimizer:
  value: adadelta
recurrent_regularizer:
  value: l2
sequence_length:
  value: 90
use_bidirectional:
  value: true
use_norm:
  value: true
use_pca:
  value: true
use_stats:
  value: false
