wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 128
dense_units:
  value: 32
dropout_rate:
  value: 0.3
epochs:
  value: 500
fusion_type:
  value: late
gru_units:
  value: 128
learning_rate:
  value: 0.005
loss:
  value: binary_crossentropy
modality:
  value: pose_audio
num_gru_layers:
  value: 1
optimizer:
  value: adam
recurrent_regularizer:
  value: l1
sequence_length:
  value: 60
use_bidirectional:
  value: true
use_norm:
  value: false
use_pca:
  value: true
use_stats:
  value: true
