wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 32
dense_units:
  value: 32
dropout_rate:
  value: 0.8
epochs:
  value: 500
fusion_type:
  value: late
gru_units:
  value: 128
learning_rate:
  value: 0.01
loss:
  value: binary_crossentropy
modality:
  value: combined
num_gru_layers:
  value: 3
optimizer:
  value: rmsprop
recurrent_regularizer:
  value: l1_l2
sequence_length:
  value: 60
use_bidirectional:
  value: true
use_norm:
  value: true
use_pca:
  value: true
use_stats:
  value: true
