wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 32
dense_units:
  value: 64
dropout_rate:
  value: 0.3
epochs:
  value: 500
fusion_type:
  value: late
gru_units:
  value: 64
learning_rate:
  value: 0.005
loss:
  value: categorical_crossentropy
modality:
  value: facial
num_gru_layers:
  value: 1
optimizer:
  value: sgd
recurrent_regularizer:
  value: l2
sequence_length:
  value: 90
use_bidirectional:
  value: false
use_norm:
  value: false
use_pca:
  value: true
use_stats:
  value: true
