wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 32
dense_units:
  value: 128
dropout_rate:
  value: 0.3
epochs:
  value: 500
fusion_type:
  value: intermediate
gru_units:
  value: 64
learning_rate:
  value: 0.01
loss:
  value: binary_crossentropy
modality:
  value: pose_audio
num_gru_layers:
  value: 1
optimizer:
  value: sgd
recurrent_regularizer:
  value: l1
sequence_length:
  value: 60
use_bidirectional:
  value: false
use_norm:
  value: true
use_pca:
  value: false
use_stats:
  value: false
