wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 64
dense_units:
  value: 64
dropout_rate:
  value: 0.8
epochs:
  value: 500
fusion_type:
  value: intermediate
gru_units:
  value: 128
learning_rate:
  value: 0.001
loss:
  value: categorical_crossentropy
modality:
  value: facial
num_gru_layers:
  value: 3
optimizer:
  value: adadelta
recurrent_regularizer:
  value: l1_l2
sequence_length:
  value: 30
use_bidirectional:
  value: false
use_norm:
  value: false
use_pca:
  value: true
use_stats:
  value: true
