wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 32
dense_units:
  value: 128
dropout_rate:
  value: 0.3
epochs:
  value: 500
fusion_type:
  value: early
gru_units:
  value: 256
learning_rate:
  value: 0.005
loss:
  value: categorical_crossentropy
modality:
  value: facial
num_gru_layers:
  value: 3
optimizer:
  value: adadelta
recurrent_regularizer:
  value: l1_l2
sequence_length:
  value: 90
use_bidirectional:
  value: true
use_norm:
  value: true
use_pca:
  value: false
use_stats:
  value: false
