wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 32
dense_units:
  value: 64
dropout_rate:
  value: 0.3
epochs:
  value: 500
fusion_type:
  value: early
gru_units:
  value: 256
learning_rate:
  value: 0.01
loss:
  value: categorical_crossentropy
modality:
  value: audio
num_gru_layers:
  value: 3
optimizer:
  value: adam
recurrent_regularizer:
  value: l1
sequence_length:
  value: 60
use_bidirectional:
  value: false
use_norm:
  value: true
use_pca:
  value: false
use_stats:
  value: false
