wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 32
dense_units:
  value: 128
dropout_rate:
  value: 0
epochs:
  value: 500
fusion_type:
  value: early
gru_units:
  value: 128
learning_rate:
  value: 0.005
loss:
  value: categorical_crossentropy
modality:
  value: pose_audio
num_gru_layers:
  value: 3
optimizer:
  value: adadelta
recurrent_regularizer:
  value: l1
sequence_length:
  value: 60
use_bidirectional:
  value: false
use_norm:
  value: false
use_pca:
  value: true
use_stats:
  value: false
