wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 64
dense_units:
  value: 64
dropout_rate:
  value: 0.5
epochs:
  value: 500
fusion_type:
  value: intermediate
gru_units:
  value: 256
learning_rate:
  value: 0.001
loss:
  value: binary_crossentropy
modality:
  value: pose_audio
num_gru_layers:
  value: 3
optimizer:
  value: adam
recurrent_regularizer:
  value: l1
sequence_length:
  value: 60
use_bidirectional:
  value: true
use_norm:
  value: true
use_pca:
  value: true
use_stats:
  value: true
