wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 128
dense_units:
  value: 32
dropout_rate:
  value: 0.5
epochs:
  value: 500
fusion_type:
  value: intermediate
gru_units:
  value: 128
learning_rate:
  value: 0.01
loss:
  value: categorical_crossentropy
modality:
  value: combined
num_gru_layers:
  value: 2
optimizer:
  value: rmsprop
recurrent_regularizer:
  value: l2
sequence_length:
  value: 90
use_bidirectional:
  value: true
use_norm:
  value: true
use_pca:
  value: false
use_stats:
  value: true
