wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 128
dense_units:
  value: 64
dropout_rate:
  value: 0.8
epochs:
  value: 500
fusion_type:
  value: late
gru_units:
  value: 256
learning_rate:
  value: 0.005
loss:
  value: binary_crossentropy
modality:
  value: pose_facial
num_gru_layers:
  value: 2
optimizer:
  value: adadelta
recurrent_regularizer:
  value: l2
sequence_length:
  value: 60
use_bidirectional:
  value: false
use_norm:
  value: true
use_pca:
  value: false
use_stats:
  value: true
