wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 64
dense_units:
  value: 32
dropout_rate:
  value: 0.8
epochs:
  value: 500
fusion_type:
  value: late
gru_units:
  value: 64
learning_rate:
  value: 0.01
loss:
  value: categorical_crossentropy
modality:
  value: facial_audio
num_gru_layers:
  value: 2
optimizer:
  value: adadelta
recurrent_regularizer:
  value: l1_l2
sequence_length:
  value: 30
use_bidirectional:
  value: false
use_norm:
  value: true
use_pca:
  value: true
use_stats:
  value: true
