wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 64
dense_units:
  value: 128
dropout_rate:
  value: 0.3
epochs:
  value: 500
fusion_type:
  value: intermediate
gru_units:
  value: 128
learning_rate:
  value: 0.01
loss:
  value: categorical_crossentropy
modality:
  value: pose_facial
num_gru_layers:
  value: 2
optimizer:
  value: rmsprop
recurrent_regularizer:
  value: l1
sequence_length:
  value: 90
use_bidirectional:
  value: false
use_norm:
  value: true
use_pca:
  value: true
use_stats:
  value: false
