wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 64
dense_units:
  value: 128
dropout_rate:
  value: 0.3
epochs:
  value: 500
fusion_type:
  value: early
gru_units:
  value: 256
learning_rate:
  value: 0.005
loss:
  value: binary_crossentropy
modality:
  value: combined
num_gru_layers:
  value: 2
optimizer:
  value: adam
recurrent_regularizer:
  value: l1_l2
sequence_length:
  value: 30
use_bidirectional:
  value: true
use_norm:
  value: true
use_pca:
  value: true
use_stats:
  value: false
