wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 64
dense_units:
  value: 32
dropout_rate:
  value: 0.3
epochs:
  value: 500
fusion_type:
  value: early
learning_rate:
  value: 0.001
loss:
  value: categorical_crossentropy
lstm_units:
  value: 128
modality:
  value: pose_audio
num_lstm_layers:
  value: 3
optimizer:
  value: rmsprop
recurrent_regularizer:
  value: l2
sequence_length:
  value: 90
use_bidirectional:
  value: false
use_norm:
  value: true
use_pca:
  value: true
use_stats:
  value: false
