wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 128
dense_units:
  value: 64
dropout_rate:
  value: 0.8
epochs:
  value: 500
fusion_type:
  value: late
learning_rate:
  value: 0.001
loss:
  value: categorical_crossentropy
lstm_units:
  value: 128
modality:
  value: pose
num_lstm_layers:
  value: 3
optimizer:
  value: adadelta
recurrent_regularizer:
  value: l2
sequence_length:
  value: 90
use_bidirectional:
  value: true
use_norm:
  value: false
use_pca:
  value: true
use_stats:
  value: true
